name: CI/CD Pipeline with Docker and Compose

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build com docker-compose
        run: docker-compose -f docker-compose.yml build

      - name: Validar sintaxe do app dentro do container
        run: docker-compose run --rm api python -m py_compile app.py #py_compile valida a sintaxe dos arquivos

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build novamente (workspace do GitHub zera)
        run: docker-compose -f docker-compose.yml build

      - name: Rodar testes unit치rios dentro do container
        run: docker-compose run --rm api python -m unittest discover -s . -p "test_*.py"


  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: production

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "$DEPLOY_GIT"
        env:
          DEPLOY_GIT: ${{ secrets.DEPLOY_GIT }}
