name: CI/CD Pipeline with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t lab_api .

      - name: Validar sintaxe do app dentro do container
        run: docker run --rm lab_api python -m py_compile app.py

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (novamente porque o workspace reseta)
        run: docker build -t lab_api .

      - name: Executar testes unit치rios dentro do container
        run: |
          docker run --rm lab_api \
            python -m unittest discover -s . -p "test_*.py"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: production

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "$DEPLOY_GIT"
        env:
          DEPLOY_GIT: ${{ secrets.DEPLOY_GIT }}
